# This configuration file is used to build an Apigee API Proxy
#
steps:
- id: 'Use apigeecli to deploy apigee artifacts to the control plane'
  name: gcr.io/apigee-product-demo/cloud-sdk:1.0.0
  entrypoint: 'bash'
  args:
  - -c
  - |
    _TOKEN=$(gcloud auth print-access-token)
    #
    ## Do the apigeecli work now
    #
    /tmp/apigeecli prefs set -s=false -o $PROJECT_ID
    /tmp/apigeecli apis create -n $_SERVICE apigee-workspace/src/main/apigee/apiproxies/catalog-proxy/apiproxy -t $_TOKEN | awk -F '"' '$2 ~ "revision"{print $4}' > /tmp/revision
    /tmp/apigeecli apis deploy -v $(cat /tmp/revision) -r -n $_SERVICE -t $_TOKEN -e $_ENV -s $_GSA@$PROJECT_ID.iam.gserviceaccount.com
