# This configuration file is used to build and deploy the app into a 
# GKE cluster using Google Cloud Build.
#
steps:
- id: 'Fetch Token and write a file'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: 
  - '-c'
  - | 
    gcloud auth print-access-token > a.token
    _TOKEN=$(cat a.token) 
    echo "---- Fetching apigeecli"
    curl -LO https://github.com/srinandan/apigeecli/releases/download/v1.104/apigeecli_v1.104_Linux_x86_64.zip
    gcloud auth print-access-token > token
- id: 'Use Token and deploy'
  name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: 'bash'
  args:
  - -c
  - |
    apt-get install -y zip
    zip -r /tmp/out.zip .
    apt-get install -y unzip zip
    unzip apigeecli_v1.104_Linux_x86_64.zip
    _APIGEE_CLI_PATH=$(pwd)/apigeecli_v1.104_Linux_x86_64
    export PATH
    echo "---- Executing apigeecli"
    cd apigee-workspace/src/main/apigee/apiproxies/catalog-proxy
    zip -r bundle.zip apiproxy
    $_APIGEE_CLI_PATH/apigeecli apis create -o apigee-product-demo -n catalog -t $(cat token) -p bundle.zip
    $_APIGEE_CLI_PATH/apigeecli apis deploy -o apigee-product-demo -n catalog -t $(cat token) -e dev-prog-proxy -s apigee-sa@apigee-product-demo.iam.gserviceaccount.com
